#!/usr/bin/env bash
# Caddy route generation, validation, installation and explicit reload.
#
# Layout (all paths relative to the site directory):
#
#   caddy/Caddyfile        tracked, generic; imports the two directories below
#   caddy/sites/*.caddy    generated, gitignored, owned by this script
#   caddy/custom/*.caddy   operator owned, gitignored, never touched here
#   caddy/snippets/*       tracked, imported by absolute path with arguments
#   caddy/.staging/        candidate tree, validated before it is installed
#
# Production uses an explicit `caddy reload`. Caddy documents `--watch` as a
# local development feature, so it is not used here.

# shellcheck disable=SC2034
GD_CADDY_LIB_LOADED=1

GD_CADDY_CONTAINER_ROOT="/etc/caddy"

# caddy_render DIR
# Renders the candidate tree into DIR/caddy/.staging/sites. Returns 1 on error.
# _caddy_site_block DOMAIN GHOST_UPSTREAM ADMIN_DOMAIN OPTIONAL_ROUTES
_caddy_site_block() {
    cat <<EOF
$1 {
	import $GD_CADDY_CONTAINER_ROOT/snippets/Logging
$4
	# Default: proxy everything else to Ghost.
	handle {
		reverse_proxy $2
	}

	# Optional: gzip compression
	encode gzip

	# Optional: security headers. The argument is mandatory: an omitted one
	# is only a Caddy warning and ships a broken frame-ancestors policy.
	import $GD_CADDY_CONTAINER_ROOT/snippets/SecurityHeaders "$3"
}
EOF
}

# caddy_render DIR
# Renders the candidate routes into DIR/caddy/.staging/sites and prints that
# path. Production only: a local site has no Caddy ingress.
caddy_render() {
    local dir=$1 env=$1/.env
    local profiles mode project domain admin url www optional ap staging required
    [[ -f $env ]] || {
        printf 'error: %s is missing\n' "$env" >&2
        return 1
    }

    profiles=$(env_get "$env" COMPOSE_PROFILES 2>/dev/null || printf '')
    mode=$(compose_site_mode "$profiles") || {
        printf 'error: COMPOSE_PROFILES=%s must name exactly one site mode\n' "$profiles" >&2
        return 1
    }
    if [[ $mode != "production" ]]; then
        printf 'error: caddy routes are only rendered in production mode (mode is %s)\n' "$mode" >&2
        return 1
    fi

    project=$(env_get "$env" COMPOSE_PROJECT_NAME 2>/dev/null || printf '')
    domain=$(env_get "$env" DOMAIN 2>/dev/null || printf '')
    for required in "$project" "$domain"; do
        [[ -n $required ]] || {
            printf 'error: COMPOSE_PROJECT_NAME and DOMAIN are required in production mode\n' >&2
            return 1
        }
    done
    admin=$(env_get "$env" ADMIN_DOMAIN 2>/dev/null || printf '')
    url=$(env_get "$env" URL 2>/dev/null || printf '')
    www=$(env_get "$env" WWW_REDIRECT 2>/dev/null || printf '')

    # Optional routes, in the order they must appear inside a site block.
    # Analytics is rendered only with its profile; ActivityPub is always
    # routed, to this site's own service or to the hosted one.
    optional=""
    case ",$profiles," in
        *,analytics,*)
            optional="
	# Traffic Analytics service
	import $GD_CADDY_CONTAINER_ROOT/snippets/TrafficAnalytics traffic-analytics-$project:3000"
            ;;
    esac
    case ",$profiles," in
        *,activitypub,*) ap="activitypub-$project:8080" ;;
        *)
            ap=$(env_get "$env" ACTIVITYPUB_TARGET 2>/dev/null || printf '')
            [[ -n $ap ]] || ap="https://ap.ghost.org"
            ;;
    esac
    optional="$optional
	# ActivityPub service
	import $GD_CADDY_CONTAINER_ROOT/snippets/ActivityPub $ap
"

    staging="$dir/caddy/.staging"
    rm -rf "$staging"
    mkdir -p "$staging/sites" || return 1

    {
        printf '# Generated by scripts/caddy.sh for %s. Do not edit.\n' "$project"
        printf '# Add your own routes as .caddy files in caddy/custom/ instead.\n\n'
        _caddy_site_block "$domain" "ghost-$project:2368" "$admin" "$optional"
        if [[ -n $admin ]]; then
            printf '\n'
            _caddy_site_block "$admin" "ghost-$project:2368" "$admin" "$optional"
        fi
        if [[ -n $www ]]; then
            printf '\n%s {\n\timport %s/snippets/Logging\n\tredir %s{uri}\n}\n' \
                "$www" "$GD_CADDY_CONTAINER_ROOT" "$url"
        fi
    } >"$staging/sites/site.caddy" || return 1

    printf '%s\n' "$staging/sites"
}

# caddy_validate DIR [SITES_DIR_IN_CONTAINER]
# Validates the tracked Caddyfile against a sites directory. Missing import
# arguments only produce a Caddy warning during adaptation, so they are
# promoted to errors here.
caddy_validate() {
    local dir=$1 sites=${2:-$GD_CADDY_CONTAINER_ROOT/sites} out rc

    out=$(compose_run "$dir" run --rm --no-deps -T \
        -e "CADDY_SITES_DIR=$sites" \
        -e "CADDY_CUSTOM_DIR=$GD_CADDY_CONTAINER_ROOT/custom" \
        -e "CADDY_GLOBAL_DIR=$GD_CADDY_CONTAINER_ROOT/global" \
        caddy caddy validate \
        --config "$GD_CADDY_CONTAINER_ROOT/Caddyfile" \
        --adapter caddyfile 2>&1)
    rc=$?

    if ((rc != 0)); then
        printf '%s\n' "$out" >&2
        return 1
    fi
    if printf '%s' "$out" | grep -q 'index is out of bounds'; then
        printf 'error: a Caddy import is missing an argument:\n%s\n' "$out" >&2
        return 1
    fi
    if printf '%s' "$out" | grep -q "No files matching import glob pattern\",\"pattern\":\"$sites"; then
        printf 'error: no site routes were found in %s\n' "$sites" >&2
        return 1
    fi
    return 0
}

# caddy_install DIR
# Atomically replaces the generated routes with the staged candidate.
# Prints the path of the backup of the previous routes.
caddy_install() {
    local dir=$1 staging=$1/caddy/.staging/sites live=$1/caddy/sites backup f base
    [[ -d $staging ]] || {
        printf 'error: nothing staged; run caddy_render first\n' >&2
        return 1
    }
    mkdir -p "$live" || return 1

    backup=$(fs_mktemp_dir ghost-docker-caddy) || return 1
    for f in "$live"/*.caddy; do
        [[ -e $f ]] || continue
        cp -p "$f" "$backup/" || return 1
    done

    # Remove generated routes that the new candidate no longer produces.
    for f in "$live"/*.caddy; do
        [[ -e $f ]] || continue
        base=$(basename "$f")
        [[ -e $staging/$base ]] || rm -f "$f"
    done

    for f in "$staging"/*.caddy; do
        [[ -e $f ]] || continue
        base=$(basename "$f")
        cat "$f" | fs_atomic_write "$live/$base" 0644 || return 1
    done

    printf '%s\n' "$backup"
}

# caddy_restore DIR BACKUP_DIR
caddy_restore() {
    local dir=$1 backup=$2 live=$1/caddy/sites f
    live="$dir/caddy/sites"
    [[ -d $backup ]] || return 1
    rm -f "$live"/*.caddy
    for f in "$backup"/*.caddy; do
        [[ -e $f ]] || continue
        cp -p "$f" "$live/" || return 1
    done
}

# caddy_running DIR
caddy_running() {
    local id
    id=$(compose_run "$1" ps -q caddy 2>/dev/null)
    [[ -n $id ]]
}

# caddy_reload DIR
# Explicit reload. Never `--watch`.
caddy_reload() {
    compose_run "$1" exec -T caddy caddy reload \
        --config "$GD_CADDY_CONTAINER_ROOT/Caddyfile" \
        --adapter caddyfile
}

# caddy_verify DIR DOMAIN...
# Confirms the reloaded server is actually routing the expected hostnames, by
# reading Caddy's own loaded configuration rather than trusting the reload
# exit status.
caddy_verify() {
    local dir=$1 cfg domain rc=0
    shift
    cfg=$(compose_run "$dir" exec -T caddy \
        wget -q -O - http://127.0.0.1:2019/config/apps/http/servers 2>/dev/null) || {
        printf 'error: could not read the running Caddy configuration\n' >&2
        return 1
    }
    for domain in "$@"; do
        [[ -n $domain ]] || continue
        if ! printf '%s' "$cfg" | grep -q "\"$domain\""; then
            printf 'error: %s is not routed by the running Caddy configuration\n' "$domain" >&2
            rc=1
        fi
    done
    return $rc
}

# caddy_apply DIR
# Render, validate, install, reload, verify. The previous on-disk configuration
# is restored if validation, reload or verification fails.
caddy_apply() {
    local dir=$1 backup env domain admin

    caddy_render "$dir" >/dev/null || return 1

    if ! caddy_validate "$dir" "$GD_CADDY_CONTAINER_ROOT/.staging/sites"; then
        printf 'error: the candidate Caddy configuration is not valid; nothing was changed\n' >&2
        return 1
    fi

    backup=$(caddy_install "$dir") || return 1

    if ! caddy_validate "$dir"; then
        printf 'error: the installed Caddy configuration failed validation; restoring the previous routes\n' >&2
        caddy_restore "$dir" "$backup"
        return 1
    fi

    if ! caddy_running "$dir"; then
        printf 'caddy is not running; routes installed, start the stack to apply them\n'
        rm -rf "$backup"
        return 0
    fi

    if ! caddy_reload "$dir"; then
        printf 'error: caddy reload failed; restoring the previous routes\n' >&2
        caddy_restore "$dir" "$backup"
        caddy_reload "$dir" || printf 'error: restoring the previous configuration also failed\n' >&2
        return 1
    fi

    env="$dir/.env"
    domain=$(env_get "$env" DOMAIN 2>/dev/null || printf '')
    admin=$(env_get "$env" ADMIN_DOMAIN 2>/dev/null || printf '')
    if ! caddy_verify "$dir" "$domain" "$admin"; then
        printf 'error: routing verification failed; restoring the previous routes\n' >&2
        caddy_restore "$dir" "$backup"
        caddy_reload "$dir" || printf 'error: restoring the previous configuration also failed\n' >&2
        return 1
    fi

    rm -rf "$backup"
    rm -rf "$dir/caddy/.staging"
    return 0
}
